name: test PR merged

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'
      - run: npm ci
      - run: npm run test
